version: "3.8"
services:
  notificador-zap-zap:
    container_name: notificador-zap-zap
    image: notificador-zap-zap:latest
    network_mode: "host"
    build:
      context: ../notificador-zap-zap/
      dockerfile: ../notificador-zap-zap/src/main/docker/Dockerfile.native
    env_file:
      - .env
  
  sera-que-chove:
    container_name: sera-que-chove
    image: sera-que-chove:latest
    depends_on:
      - notificador-zap-zap
    network_mode: "host"
    build:
      context: ../sera-que-chove/
      dockerfile: ../sera-que-chove/Dockerfile
    env_file:
      - .env